trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - main

jobs:
  - job: RunTests
    displayName: 'Run TestNG Tests'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        displayName: 'Checkout code'

      - task: JavaToolInstaller@0
        displayName: 'Set up JDK'
        inputs:
          versionSpec: '17'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'

      - task: Cache@2
        displayName: 'Cache Maven dependencies'
        inputs:
          key: 'maven | "$(Agent.OS)" | **/pom.xml'
          restoreKeys: |
            maven | "$(Agent.OS)"
          path: $(HOME)/.m2/repository

      - script: mvn clean install -DskipTests
        displayName: 'Install dependencies'

      - script: |
          mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"
        displayName: 'Install Playwright system dependencies'

      - script: |
          mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"
        displayName: 'Install Playwright browsers'

      - script: |
          mvn test -Dsurefire.suiteXmlFiles=TestEN.xml
        displayName: 'Run TestNG suite'
        continueOnError: true

      - task: PublishAllureReport@1
        displayName: 'Publish Allure Report'
        condition: always()
        inputs:
          testResultsDir: 'target/allure-results'

      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        condition: always()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          failTaskOnFailedTests: false